### ISSUE TITLE
JSeetaface6.dll 加载出现问题

### ISSUE THREAD

**Issue by 1369521908** [CongCongBig/JSeetaface6#3]
D:/work/JSeetaface6/target/classes/x64/JSeetaFace6.dll
java.lang.UnsatisfiedLinkError: D:\work\JSeetaface6\target\classes\x64\JSeetaface6.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at cn.yezhss.seetaface.demo.base.SeetafaceTest.<clinit>(SeetafaceTest.java:69)
Disconnected from the target VM, address: '127.0.0.1:57842', transport: 'socket'
Exception in thread "main" 
Process finished with exit code 1

maven编译通过
classes里面东西都有

**Comment by 1369521908** [comment]
官方的dll库存放路径还有模型库存放路径都跟README.md里面一致

**Comment by CongCongBig** [comment]
maven打包没有配置过滤，dll会被排在外面，暂时只能在编辑器上执行，因为它只是一个仅供参考的demo。

**Comment by CongCongBig** [comment]
检查一下那堆System.load是否有执行

**Comment by 1369521908** [comment]
感谢回复, 前面那堆没问题 (能正常往下执行),就是最后那个(JSeetaface6.dll)加载出问题了

**Comment by 1369521908** [comment]
找到解决方法了,安装了一些基础库就好了
百度了这个 微软常用运行库合集 装上就OK了
我是试了那个python版的找出来的解决方法
https://github.com/tensorflower/seetaFace6Python
